<?php
/**
 * Implements hook_theme().
 */
function fb_search_theme($existing, $type, $theme, $path) {
  return [
    'search-results' => [
      'variables' => [
        'response' => NULL,
        'results' => NULL,
        'q' => NULL,
        'place' => NULL,
        'rows' => NULL,
        'form' => NULL,
       ],
      'render element' => 'form',
    ],
    'landing-page' => [
      'render element' => 'form',
    ],
    'display-object' =>[
      'variables' => ['object' => NULL],
    ],
  ];
}
?>
